# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0002_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
