# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0003_auto_20170821_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='images/image'),
        ),
    ]
