# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0004_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='images/image', max_length=70),
        ),
    ]
