# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0005_auto_20170821_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
